export const nameCar = [
  { id: 1, name: "MINI" },
  { id: 2, name: "Buick" },
  { id: 3, name: "Volvo" },
  { id: 4, name: "Ford" },
  { id: 5, name: "HUMMER" },
  { id: 6, name: "GMC" },
  { id: 7, name: "Subaru" },
  { id: 8, name: "Mitsubishi" },
  { id: 9, name: "Dodge" },
  { id: 10, name: "Nissan" },
  { id: 11, name: "Honda" },
  { id: 12, name: "Lincoln" },
  { id: 13, name: "Hyundai" },
  { id: 14, name: "BMW" },
  { id: 15, name: "Bentley" },
  { id: 16, name: "Lexus" },
  { id: 17, name: "Chevrolet" },
  { id: 18, name: "Jaguar" },
  { id: 19, name: "Mercedes-Benz" },
  { id: 20, name: "Volkswagen" },
  { id: 21, name: "Aston Martin" },
  { id: 22, name: "Land Rover" },
  { id: 23, name: "Pontiac" },
  { id: 24, name: "Cadillac" },
  { id: 25, name: "FIAT" },
  { id: 26, name: "Saab" },
  { id: 27, name: "Kia" },
  { id: 28, name: "Lamborghini" },
  { id: 29, name: "Audi" },
  { id: 30, name: "Jeep" },
  { id: 31, name: "MAZDA" },
  { id: 32, name: "Suzuki" },
  { id: 33, name: "Toyota" },
  { id: 34, name: "Acura" },
  { id: 35, name: "Saturn" },
  { id: 36, name: "Chrysler" },
  { id: 37, name: "Isuzu" },
  { id: 38, name: "Ferrari" },
  { id: 39, name: "Tesla" },
  { id: 40, name: "INFINITI" },
  { id: 41, name: "Oldsmobile" },
  { id: 42, name: "Ram" },
  { id: 43, name: "Eagle" },
  { id: 44, name: "Porsche" },
  { id: 45, name: "Mercury" },
  { id: 46, name: "Scion" },
  { id: 47, name: "Lotus" },
  { id: 48, name: "Plymouth" },
  { id: 49, name: "Freightliner" },
  { id: 50, name: "Rolls-Royce" },
  { id: 51, name: "SRT" },
  { id: 52, name: "Maybach" },
  { id: 53, name: "Alfa Romeo" },
  { id: 54, name: "Geo" },
  { id: 55, name: "smart" },
  { id: 56, name: "Daewoo" },
  { id: 57, name: "Maserati" },
  { id: 58, name: "Daihatsu" },
  { id: 59, name: "Genesis" },
  { id: 60, name: "McLaren" },
  { id: 61, name: "Fisker" },
  { id: 62, name: "Panoz" },
];
export const modelCar = [
  { id: 1, name: "SUV" },
  { id: 2, name: "Convertible" },
  { id: 3, name: "Pickup" },
  { id: 4, name: "Van/Minivan" },
  { id: 5, name: "Wagon" },
  { id: 6, name: "Sedan" },
  { id: 7, name: "Coupe" },
  { id: 8, name: "Hatchback" },
];
export const yearCar = [
  { id: 1, value: 1992 },
  { id: 2, value: 1993 },
  { id: 3, value: 1994 },
  { id: 4, value: 1995 },
  { id: 5, value: 1996 },
  { id: 6, value: 1997 },
  { id: 7, value: 1998 },
  { id: 8, value: 1999 },
  { id: 9, value: 2000 },
  { id: 10, value: 2001 },
  { id: 11, value: 2002 },
  { id: 12, value: 2003 },
  { id: 13, value: 2004 },
  { id: 14, value: 2005 },
  { id: 15, value: 2006 },
  { id: 16, value: 2007 },
  { id: 17, value: 2008 },
  { id: 18, value: 2009 },
  { id: 19, value: 2010 },
  { id: 20, value: 2011 },
  { id: 21, value: 2012 },
  { id: 22, value: 2013 },
  { id: 23, value: 2014 },
  { id: 24, value: 2015 },
  { id: 25, value: 2016 },
  { id: 26, value: 2017 },
  { id: 27, value: 2018 },
  { id: 28, value: 2019 },
  { id: 29, value: 2020 },
];
export const fuel = [
  { id: 1, name: "Xăng" },
  { id: 2, name: "Dầu Diesel" },
  { id: 3, name: "Điện" },
];
