export const nameCar = [
  {
    id: 1,
    name: "Audi",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Audi.png",
  },
  {
    id: 2,
    name: "Baic",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Baic.png",
  },
  {
    id: 3,
    name: "BMW",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/BMW.png",
  },
  {
    id: 4,
    name: "Chevrolet",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Chevrolet.png",
  },
  {
    id: 5,
    name: "Daewoo",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Daewoo.png",
  },
  {
    id: 6,
    name: "Ford",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Ford.png",
  },
  {
    id: 7,
    name: "Honda",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Honda.png",
  },
  {
    id: 8,
    name: "Hyundai",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Hyundai.png",
  },
  {
    id: 9,
    name: "Isuzu",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Isuzu.png",
  },
  {
    id: 10,
    name: "Kia",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Kia.png",
  },
  {
    id: 11,
    name: "Land Rover",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Land-Rover.png",
  },
  {
    id: 12,
    name: "Lexus",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Lexus.png",
  },
  {
    id: 13,
    name: "Mazda",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mazda.png",
  },
  {
    id: 14,
    name: "Mercedes",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mercedes.png",
  },
  {
    id: 15,
    name: "Mitsubishi",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mitsubishi.png",
  },
  {
    id: 16,
    name: "Morris Garages",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Morris-Garages.png",
  },
  {
    id: 17,
    name: "Nissan",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Nissan.png",
  },
  {
    id: 18,
    name: "Peugeot",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Peugeot.png",
  },
  {
    id: 19,
    name: "SsangYong",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Ssangyong.png",
  },
  {
    id: 20,
    name: "Suzuki",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Suzuki.png",
  },
  {
    id: 21,
    name: "Toyota",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Toyota.png",
  },
  {
    id: 22,
    name: "Vinfast",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Vinfast.png",
  },
  {
    id: 23,
    name: "Volkswagen",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Volkswagen.png",
  },
];
export const modelCar = [
  { id: 1, name: "SUV" },
  { id: 2, name: "Convertible" },
  { id: 3, name: "Pickup" },
  { id: 4, name: "Van/Minivan" },
  { id: 5, name: "Wagon" },
  { id: 6, name: "Sedan" },
  { id: 7, name: "Coupe" },
  { id: 8, name: "Hatchback" },
];
export const yearCar = [
  { id: 1, value: 1992 },
  { id: 2, value: 1993 },
  { id: 3, value: 1994 },
  { id: 4, value: 1995 },
  { id: 5, value: 1996 },
  { id: 6, value: 1997 },
  { id: 7, value: 1998 },
  { id: 8, value: 1999 },
  { id: 9, value: 2000 },
  { id: 10, value: 2001 },
  { id: 11, value: 2002 },
  { id: 12, value: 2003 },
  { id: 13, value: 2004 },
  { id: 14, value: 2005 },
  { id: 15, value: 2006 },
  { id: 16, value: 2007 },
  { id: 17, value: 2008 },
  { id: 18, value: 2009 },
  { id: 19, value: 2010 },
  { id: 20, value: 2011 },
  { id: 21, value: 2012 },
  { id: 22, value: 2013 },
  { id: 23, value: 2014 },
  { id: 24, value: 2015 },
  { id: 25, value: 2016 },
  { id: 26, value: 2017 },
  { id: 27, value: 2018 },
  { id: 28, value: 2019 },
  { id: 29, value: 2020 },
];
export const fuel = [
  { id: 1, name: "Xăng" },
  { id: 2, name: "Dầu Diesel" },
  { id: 3, name: "Điện" },
];

export const listCar = [
  {
    id: 1,
    codeCar: "51A12323",
    branchCar: "Audi",
    typeCar: "SUV",
    countChairs: 4,
    date: "2023",
    motor: "Số tự động",
    fuelType: "Xăng",
    number_constructor: "2132133312",
    driver_type: "Có tài xế",
    fuel_weight: 10,
    describe: "Xe Audi",
    features: {
      map: true,
      bluetooth: true,
      camera360: true,
      camera_truoc: true,
      camera_trip: true,
      camera_sau: false,
      window: true,
      gps: true,
      chair_child: true,
      tire_expand: true,
      dvd: true,
      air_bag: true,
    },
    price: 2400000,
    address: {
      city: "Quảng Ngãi",
      district: "Huyện Tư Nghĩa",
      ward: "Xẫ Nghĩa Phương",
    },
    required_rent: true,
    img: [
      {
        id: 1,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/honda_city_2020/p/g/2022/10/21/15/znRxesa9cQqY3gxW99VMuQ.jpg",
      },
      {
        id: 2,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/honda_city_2020/p/g/2022/10/21/15/T8iNs6w2YcGp2zVzofb3yg.jpg",
      },
      {
        id: 3,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/honda_city_2020/p/g/2022/11/03/14/y4lymYDb1lq8B-EQocSFmg.jpg",
      },
      {
        id: 4,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/honda_city_2020/p/g/2022/10/21/15/Iipirxa_MxMx96iKkKtSpw.jpg",
      },
    ],
    rate: 4.0,
    total_trip: 3,
    owner: {
      id: 1,
      first_name: "Bảo",
      last_name: "Cao Minh",
      email: "minhbao11b3@gmail.com",
      address: "Quảng Ngãi",
      phone: 424255221,
    },
  },
  {
    id: 2,
    codeCar: "52A54355",
    branchCar: "BMW",
    typeCar: "Wagon",
    countChairs: 7,
    date: "2022",
    motor: "Số sàn",
    fuelType: "Xăng",
    number_constructor: "43244324234",
    driver_type: "Không có tài xế",
    fuel_weight: 60,
    describe: "Xe BMW",
    features: {
      map: true,
      bluetooth: true,
      camera360: true,
      camera_truoc: true,
      camera_trip: true,
      camera_sau: false,
      window: true,
      gps: true,
      chair_child: true,
      tire_expand: true,
      dvd: true,
      air_bag: true,
    },
    price: 1400000,
    address: {
      city: "Thành Phố Hồ Chí Minh",
      district: "Quận 1",
      ward: "Phường Bến Nghé",
    },
    required_rent: false,
    img: [
      {
        id: 1,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/bmw_320i__2013/p/g/2023/02/24/16/4bBclsR0qNgp3ZoQRbmUBg.jpg",
      },
      {
        id: 2,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/bmw_320i__2013/p/g/2023/02/24/16/FNoU4l7040O_BAPVzBAPEw.jpg",
      },
      {
        id: 3,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/bmw_320i__2013/p/g/2023/02/24/16/O-m7yef1dmvsYgorG3dpmA.jpg",
      },
      {
        id: 4,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/bmw_320i__2013/p/g/2023/02/24/16/IZK1xCtN5AvagRSuaq64kg.jpg",
      },
    ],
    rate: 4.5,
    total_trip: 5,
    owner: {
      id: 1,
      first_name: "Bảo",
      last_name: "Cao Minh",
      email: "minhbao11b3@gmail.com",
      address: "Quảng Ngãi",
      phone: 4234234,
    },
  },
  {
    id: 3,
    codeCar: "76A13456",
    branchCar: "Toyota",
    typeCar: "Convertible",
    countChairs: 5,
    date: "2022",
    motor: "Số sàn",
    fuelType: "Xăng",
    number_constructor: "43244324234",
    driver_type: "Không có tài xế",
    fuel_weight: 60,
    describe: "Xe Toyota",
    features: {
      map: true,
      bluetooth: true,
      camera360: true,
      camera_truoc: true,
      camera_trip: true,
      camera_sau: false,
      window: true,
      gps: true,
      chair_child: true,
      tire_expand: true,
      dvd: true,
      air_bag: true,
    },
    price: 1400000,
    address: {
      city: "Thành Phố Hồ Chí Minh",
      district: "Quận 1",
      ward: "Phường Bến Nghé",
    },
    required_rent: false,
    img: [
      {
        id: 1,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/toyota_veloz_cross_2022/p/g/2022/05/01/08/7zPe_hHomjRYLaeCiEy60Q.jpg",
      },
      {
        id: 2,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/toyota_veloz_cross_2022/p/g/2022/05/01/08/sHHCN5pVn0VFzTqfld6xKw.jpg",
      },
      {
        id: 3,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/toyota_veloz_cross_2022/p/g/2022/05/01/08/mv5AEM_MMCSSwhk_QfdBAw.jpg",
      },
      {
        id: 4,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/toyota_veloz_cross_2022/p/g/2022/05/01/08/xYdfm78JKxLjhMoyJE0mfw.jpg",
      },
    ],
    rate: 4.7,
    total_trip: 10,
    owner: {
      id: 1,
      first_name: "Bảo",
      last_name: "Cao Minh",
      email: "minhbao11b3@gmail.com",
      address: "Quảng Ngãi",
      phone: 234234234,
    },
  },
  {
    id: 4,
    codeCar: "79A13456",
    branchCar: "Suzuki",
    typeCar: "Hatchback",
    countChairs: 7,
    date: "2014",
    motor: "Số sàn",
    fuelType: "Xăng",
    number_constructor: "43244324234",
    driver_type: "Không có tài xế",
    fuel_weight: 70,
    describe: "Xe Suzuki",
    features: {
      map: true,
      bluetooth: true,
      camera360: true,
      camera_truoc: true,
      camera_trip: true,
      camera_sau: false,
      window: true,
      gps: true,
      chair_child: true,
      tire_expand: true,
      dvd: true,
      air_bag: true,
    },
    price: 1921000,
    address: {
      city: "Hà Nội",
      district: "Quận Ba Đình",
      ward: "Phường Điện Biên",
    },
    required_rent: false,
    img: [
      {
        id: 1,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/04/22/RFZcdv6LUZBCF2J3DwfBjw.jpg",
      },
      {
        id: 2,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/19/21/Ov6rfCHCtJVpgMJ1EJNaTg.jpg",
      },
      {
        id: 3,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/19/21/oEaL-htqZAyJloc3BKrJjw.jpg",
      },
      {
        id: 4,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/04/21/17/ZE1P4qF03NSBf7L349fQgA.jpg",
      },
    ],
    rate: 4.5,
    total_trip: 20,
    owner: {
      id: 1,
      first_name: "Bảo",
      last_name: "Cao Minh",
      email: "minhbao11b3@gmail.com",
      address: "Quảng Ngãi",
      phone: 42344234,
    },
  },
  {
    id: 5,
    codeCar: "79A13456",
    branchCar: "Suzuki",
    typeCar: "Hatchback",
    countChairs: 7,
    date: "2014",
    motor: "Số sàn",
    fuelType: "Xăng",
    number_constructor: "43244324234",
    driver_type: "Không có tài xế",
    fuel_weight: 70,
    describe: "Xe Suzuki",
    features: {
      map: true,
      bluetooth: true,
      camera360: true,
      camera_truoc: true,
      camera_trip: true,
      camera_sau: false,
      window: true,
      gps: true,
      chair_child: true,
      tire_expand: true,
      dvd: true,
      air_bag: true,
    },
    price: 1921000,
    address: {
      city: "Hà Nội",
      district: "Quận Ba Đình",
      ward: "Phường Điện Biên",
    },
    required_rent: true,
    img: [
      {
        id: 1,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/04/22/RFZcdv6LUZBCF2J3DwfBjw.jpg",
      },
      {
        id: 2,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/19/21/Ov6rfCHCtJVpgMJ1EJNaTg.jpg",
      },
      {
        id: 3,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/01/19/21/oEaL-htqZAyJloc3BKrJjw.jpg",
      },
      {
        id: 4,
        url: "https://n1-pstg.mioto.vn/cho_thue_xe_o_to_tu_lai_thue_xe_du_lich_hochiminh/suzuki_xl7_2021/p/g/2023/04/21/17/ZE1P4qF03NSBf7L349fQgA.jpg",
      },
    ],
    rate: 4.5,
    total_trip: 20,
    owner: {
      id: 1,
      first_name: "Bảo",
      last_name: "Cao Minh",
      email: "minhbao11b3@gmail.com",
      address: "Quảng Ngãi",
      phone: 42344234,
    },
  },
];
