export const nameCar = [
  {
    id: 1,
    name: "Audi",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Audi.png",
  },
  {
    id: 2,
    name: "Baic",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Baic.png",
  },
  {
    id: 3,
    name: "BMW",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/BMW.png",
  },
  {
    id: 4,
    name: "Chevrolet",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Chevrolet.png",
  },
  {
    id: 5,
    name: "Daewoo",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Daewoo.png",
  },
  {
    id: 6,
    name: "Ford",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Ford.png",
  },
  {
    id: 7,
    name: "Honda",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Honda.png",
  },
  {
    id: 8,
    name: "Hyundai",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Hyundai.png",
  },
  {
    id: 9,
    name: "Isuzu",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Isuzu.png",
  },
  {
    id: 10,
    name: "Kia",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Kia.png",
  },
  {
    id: 11,
    name: "Land Rover",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Land-Rover.png",
  },
  {
    id: 12,
    name: "Lexus",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Lexus.png",
  },
  {
    id: 13,
    name: "Mazda",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mazda.png",
  },
  {
    id: 14,
    name: "Mercedes",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mercedes.png",
  },
  {
    id: 15,
    name: "Mitsubishi",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Mitsubishi.png",
  },
  {
    id: 16,
    name: "Morris Garages",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Morris-Garages.png",
  },
  {
    id: 17,
    name: "Nissan",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Nissan.png",
  },
  {
    id: 18,
    name: "Peugeot",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Peugeot.png",
  },
  {
    id: 19,
    name: "SsangYong",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Ssangyong.png",
  },
  {
    id: 20,
    name: "Suzuki",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Suzuki.png",
  },
  {
    id: 21,
    name: "Toyota",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Toyota.png",
  },
  {
    id: 22,
    name: "Vinfast",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Vinfast.png",
  },
  {
    id: 23,
    name: "Volkswagen",
    logo: "https://n1-cstg.mioto.vn/m/vehicle-makes/Volkswagen.png",
  },
];
export const modelCar = [
  { id: 1, name: "SUV" },
  { id: 2, name: "Convertible" },
  { id: 3, name: "Pickup" },
  { id: 4, name: "Van/Minivan" },
  { id: 5, name: "Wagon" },
  { id: 6, name: "Sedan" },
  { id: 7, name: "Coupe" },
  { id: 8, name: "Hatchback" },
];
export const yearCar = [
  { id: 1, value: 1992 },
  { id: 2, value: 1993 },
  { id: 3, value: 1994 },
  { id: 4, value: 1995 },
  { id: 5, value: 1996 },
  { id: 6, value: 1997 },
  { id: 7, value: 1998 },
  { id: 8, value: 1999 },
  { id: 9, value: 2000 },
  { id: 10, value: 2001 },
  { id: 11, value: 2002 },
  { id: 12, value: 2003 },
  { id: 13, value: 2004 },
  { id: 14, value: 2005 },
  { id: 15, value: 2006 },
  { id: 16, value: 2007 },
  { id: 17, value: 2008 },
  { id: 18, value: 2009 },
  { id: 19, value: 2010 },
  { id: 20, value: 2011 },
  { id: 21, value: 2012 },
  { id: 22, value: 2013 },
  { id: 23, value: 2014 },
  { id: 24, value: 2015 },
  { id: 25, value: 2016 },
  { id: 26, value: 2017 },
  { id: 27, value: 2018 },
  { id: 28, value: 2019 },
  { id: 29, value: 2020 },
];
export const fuel = [
  { id: 1, name: "Xăng" },
  { id: 2, name: "Dầu Diesel" },
  { id: 3, name: "Điện" },
];
